# Use postgres/example user/password credentials
#docker-compose -f mongo.yml up -d
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: paulo123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080